version: "3.1"
services:
    mysql:
      image: mysql:8.0
      container_name: weerwolven-mysql
      command: --default-authentication-plugin=mysql_native_password
      volumes:
        - ./database_data:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=admin
        - MYSQL_DATABASE=weerwolven
        - MYSQL_USER=admin
        - MYSQL_PASSWORD=admin
      ports:
        - "127.0.0.1:1234:3306"
